### ISSUE TITLE
Please revise the code and documentation

### ISSUE THREAD

**Issue by smetronic** [deshi-basara/libELM#1]
I have installed your library but it doesn't work, below are errors:
`C:\Users\Admin\Documents\Arduino\libraries\libELM-master\elm.cpp:178:20: error: qualified-id in declaration before '(' token

 String ELM::get_vin() { // tested (without vehicle), response is NO DATA, works

                    ^

C:\Users\Admin\Documents\Arduino\libraries\libELM-master\elm.cpp:186:20: error: qualified-id in declaration before '(' token

 String ELM::get_ecu() { // tested (without vehicle), response is NO DATA, works

                    ^

C:\Users\Admin\Documents\Arduino\libraries\libELM-master\elm.cpp:194:24: error: qualified-id in declaration before '(' token

 String ELM::get_voltage() { // tested, works

                        ^

C:\Users\Admin\Documents\Arduino\libraries\libELM-master\elm.cpp:202:25: error: qualified-id in declaration before '(' token

 String ELM::get_protocol() { // tested, works

                         ^

C:\Users\Admin\Documents\Arduino\libraries\libELM-master\elm.cpp:478:1: error: expected '}' at end of input

 }

 ^

exit status 1
Error compiling for board Arduino/Genuino Uno.`

Thanks

**Comment by deshi-basara** [comment]
Thanks for your contribution!

This project isn't actively maintained anymore by my colleges and me - so feel free to fork this project :thumbsup:
